public with sharing class MyClass {

    public static void hello() {
        System.debug('Hello World');
    }

    public static void hello2() {
        System.debug('Hello World!!!');
    }

    public static void hello3() {
        System.debug('Jan Kowalski');
    }

    public static void deploy() {
        System.debug('Let\'s deploy me!!!!!!!!!');
        System.debug('Deploying...');
        System.debug('CRM');
        System.debug('');
        System.debug('Deploy me!');
        System.debug('Let\'s deploy me!!!!!!!!!!!!');
    }
}